### ISSUE TITLE
which icons can be used.

### ISSUE THREAD

**Issue by Aw0d** [rivafarabi/deckboard-kit#6]
Is there a list of icons that can be used when creating an extension?

**Comment by rivafarabi** [comment]
You can use [FontAwesome5 Free](https://fontawesome.com/icons?d=gallery&m=free) icons by passing the icon name string and `fontIcon` like example below

```
this.inputs = [
	{
		label: 'Launch Game',
		value: 'steam-launch-games',
		icon: 'steam',
		fontIcon: 'fab',
		color: '#171A21',
		input: [
			{
				label: 'Game',
				ref: 'appid',
				type: INPUT_METHOD.INPUT_SELECT,
				items: this.getGameList()
			}
		]
	}
];
```

For the `fontIcon` object, use `fas`, `far`, or `fab` for solid, regular, or brand icon.

**Comment by Aw0d** [comment]
Okay, thank you
